name: Gfxstream Postsubmit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  postsubmit-populate-bazel-cache:
    runs-on: ubuntu-22.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true

    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

    - name: Install bazel
      run: sudo bash toolchain/bazel/install_bazel.sh

    - name: Install toolchain dependencies
      run: sudo bash toolchain/bazel/install_toolchain_dependencies.sh

    - name: Mount Bazel cache
      uses: ./.github/actions/mount-bazel-cache
      with:
        bazel-build-config-name: "default"
        writable: true

    - name: Build
      run: |
        bazel build ... \
          --disk_cache=$HOME/bazel-disk-cache \
          --graphics_drivers=gles_angle_vulkan_swiftshader \
          --verbose_failures

    postsubmit-populate-bazel-cache-asan:
    runs-on: ubuntu-22.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true

    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

    - name: Install bazel
      run: sudo bash toolchain/bazel/install_bazel.sh

    - name: Install toolchain dependencies
      run: sudo bash toolchain/bazel/install_toolchain_dependencies.sh

    - name: Mount Bazel cache
      uses: ./.github/actions/mount-bazel-cache
      with:
        bazel-build-config-name: "asan"
        writable: true

    - name: Build
      run: |
        bazel build ... \
          --config=asan \
          --disk_cache=$HOME/bazel-disk-cache \
          --graphics_drivers=gles_angle_vulkan_swiftshader \
          --verbose_failures

  postsubmit-populate-bazel-cache-arm:
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true

    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

    - name: Install bazel
      run: sudo bash toolchain/bazel/install_bazel.sh

    - name: Install toolchain dependencies
      run: sudo bash toolchain/bazel/install_toolchain_dependencies.sh

    - name: Mount Bazel cache
      uses: ./.github/actions/mount-bazel-cache
      with:
        bazel-build-config-name: "default"
        writable: true

    - name: Build
      run: |
        bazel build ... \
          --disk_cache=$HOME/bazel-disk-cache \
          --graphics_drivers=gles_angle_vulkan_swiftshader \
          --verbose_failures
