name: Gfxstream Postsubmit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: read

jobs:
  postsubmit-populate-bazel-cache-lavapipe:
    uses: ./.github/workflows/postsubmit_bazel.yml
    with:
      additional-bazel-args: --graphics_drivers=gles_angle_vulkan_lavapipe
      cache-config: lavapipe
      runner: ubuntu-22.04

  postsubmit-populate-bazel-cache-swiftshader:
    uses: ./.github/workflows/postsubmit_bazel.yml
    with:
      additional-bazel-args: --graphics_drivers=gles_angle_vulkan_swiftshader
      cache-config: swiftshader
      runner: ubuntu-22.04

  postsubmit-populate-bazel-cache-swiftshader-asan:
    uses: ./.github/workflows/postsubmit_bazel.yml
    with:
      additional-bazel-args: --graphics_drivers=gles_angle_vulkan_swiftshader --config=asan
      cache-config: swiftshader-asan
      runner: ubuntu-22.04

  postsubmit-populate-bazel-cache-arm:
    uses: ./.github/workflows/postsubmit_bazel.yml
    with:
      runner: ubuntu-22.04-arm

  postsubmit-populate-bazel-cache-macos:
    uses: ./.github/workflows/postsubmit_bazel.yml
    with:
      runner: macos-26
      build-targets: >-
        //host:gfxstream_backend_static
        //host:gfxstream_backend_shared
        //host:gfxstream_backend
        //common/base:gfxstream_common_base_tests
